# This is the configuration used to check the rubocop source code.

AllCops:
  NewCops: enable
  Exclude:
    - 'test/fixtures/*'

Style/StringLiterals:
  Enabled: true

Style/RedundantPercentQ:
  Enabled: true

# Disabled Checks
Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false
