sudo: false
branches:
  except:
  - gh-pages
cache: bundler
language: ruby
rvm:
  - 2.2.2
before_install:
  - gem update --remote bundler
install:
  - bundle install --retry=3
script:
  - bundle exec rake test
  - bundle exec rake rubocop
deploy:
  provider: heroku
  app: pizza-calc
  api_key:
    secure: x8iniLs9BYRjiov4A7y2XSNczDiTje/DDIALQNKDxYjmcr6iAhDMCZDxlC6UZEpOLytNrzoPlrlZyxIpNPPV5vi0kju9kR8NlcIRGgG66OorazBDgnm5Tcb5VlcVUiLp6ePPgZ4OXpd8PxDRQEmsITub415MFh9OvF1AZsMNvvozqJMPEDstVH2tcftQ5JJctD7z7yz5zX+BjHdeB0IEL9ukkI3D/dFt4Tl3llaC+QQgoF2kiTrLwvnNQTKZ97oug/8beLLRccEAGIQEwFYms7HbI9qd1N9pMMf4Jz9hB4TfQHOVRBqMOsfe4tno9q5Hq/cjaDgoA3fKysEx5HZYIRBj7kwxgwlz0LoASofNxuLCmWVUCMs3cvgqUEepCM3KDR94zF3X7C7MNb2VYZJbBH2tz2B2E0QV6EiGGhbYQZd05CEwN/3OwI9u8RLVrsaCsSGFkV1EV3L9gelccJ/TD/Ny+N9s/8UaSoUivArlK6bVo0BsyB8zOnBxDO0CePzXiFZtJD/pFHpZQZB6YdYwqcjQ9yxtrOTaI7l8YoH/4mJN5OGlPAtP1JZA2BJ4aotx/CMQ4US0w8H1swSOb42UBejB6Iu8FvnzHWhusLbbQH2hyLsAbEHuyUiI8lB/r6b8JjREBO17fmudp3cvpZpkq7PJxD+fUzkH8iIO1zoaAPc=
